const treatments = [
  {
    label: "Smile Designing",
    href: "/treatments/smile-design",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Root Canal",
    href: "/treatments/root-canal",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Ultrasonic Scaling",
    href: "/treatments/ultrasonic-scaling",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Removable Denture, Cast Partial Denture & Flexible Partial Denture",
    href: "/treatments/removable-denture-cast-partial-denture-and-flexible-partial-denture",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Crown/Capping & Fixed Bridge Works (Metal, PFM, Full Ceramic)",
    href: "/treatments/crown-capping-and-fixed-bridge-works",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Whitening Of Teeth",
    href: "/treatments/white-of-teeth",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Treatment Of Uneven Tooth",
    href: "/treatments/treatment-of-uneven-tooth",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Frenectomy & Frenuloplasty",
    href: "/treatments/frenectomy-and-frenuloplasty",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Dental Implant",
    href: "/treatments/dental-implant",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Oral & Maxillofacial Surgery",
    href: "/treatments/oral-and-maxillofacial-surgery",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Oral Dental Preventive Services",
    href: "/treatments/oral-dental-preventive-services",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Depigmentation Of Gums",
    href: "/treatments/depigmentation-of-gums",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Pediatric Dentistry",
    href: "/treatments/pediatric-dentistry",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Piezoelectric Surgery",
    href: "/treatments/piezoelectric-surgery",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Dental Veneer & Thinner",
    href: "/treatments/dental-veneer-and-thinner",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Ethical Dentistry & Affordability",
    href: "/treatments/ethical-dentistry-and-affordability",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Treatment Of All Kinds Of Oral And Dental Diseases",
    href: "/treatments/treatment-of-all-kinds-of-oral-and-dental-diseases",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Tumor, Cyst Surgery & Treatment Of Jaw Fracture",
    href: "/treatments/tumor-cyst-surgery-and-treatment-of-jaw-fracture",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Oral Prophylaxis, Tooth Care",
    href: "/treatments/oral-prophylaxis-tooth-care",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Maxillofacial Prosthesis",
    href: "/treatments/maxillofacial-prosthesis",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Wisdom Tooth Surgery",
    href: "/treatments/wisdom-tooth-surgery",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Painless Tooth Extraction",
    href: "/treatments/painless-tooth-extraction",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Laser Surgery",
    href: "/treatments/laser-surgery",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Micro Surgery",
    href: "/treatments/micro-surgery",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Electro Surgery",
    href: "/treatments/electro-surgery",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Surgical Exposure of Impacted/Timely Non-Erupted Front Tooth/Teeth",
    href: "/treatments/surgical-exposure-of-impacted-timely-non-erupted-front-tooth",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Autoclave",
    href: "/treatments/autoclave",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Portable Dental X-Ray Machine",
    href: "/treatments/portable-dental-x-ray-machine",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Cosmetic Intraoral Surgery",
    href: "/treatments/cosmetic-intraoral-surgery",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Gum Surgery & Periodontal Surgery",
    href: "/treatments/gum-surgery-and-periodontal-surgery",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Correction of Gaps/Spaces Between Teeth",
    href: "/treatments/correction-of-gaps-spaces-between-teeth",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Orofacial Physiotherapy",
    href: "/treatments/orofacial-physiotherapy",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Dental Jewellery",
    href: "/treatments/dental-jewellery",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Invisalign",
    href: "/treatments/invisalign",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Tooth Vitality Test",
    href: "/treatments/tooth-vitality-test",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Dental Lab Work",
    href: "/treatments/dental-lab-work",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Treatment of Fractured, Broken Tooth",
    href: "/treatments/treatment-of-fractured-broken-tooth",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Geriatric Dentistry",
    href: "/treatments/geriatric-dentistry",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Apicoectomy Surgery",
    href: "/treatments/apicoectomy-surgery",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
  {
    label: "Artificial Teeth",
    href: "/treatments/artificial-teeth",
    icon: "/images/serviceicon.svg",
    imgsrc: "/images/serviceimg.png",
    desc: "Lorem ipsum dolor sit amet consectetur. Tristique ac pretium elementum viverra. A suspendisse tristique magna gravida mattis. Quam eros nam.",
  },
];

export { treatments as Treatments };
